// How people actually say it. The stylist's vocabulary, learned OFFLINE (a
// Claude Code session reading how beauty is talked about on the internet —
// skincare and curly-hair forums, TikTok and YouTube captions, product
// reviews — and writing the words down here) so that the app can route a
// message by matching, at zero tokens and in no time. Grow these tables
// from real misses (`lexicon_test.ts` is the simulated corpus; a miss there
// is a row to add here); never from a model at runtime.
//
// Every entry is lowercase and matched on word boundaries, so "spf" matches
// "spf?" and "wash day" matches "wash-day"; a phrase is a plain sequence
// of words. Order in a list does not matter. Pure data plus two helpers.

/// Anything that sounds like a condition, a prescription or pain: the
/// stylist declines to diagnose and stays on the beauty half. Checked
/// FIRST, before any other word can claim the message.
export const MEDICAL_WORDS: readonly string[] = [
  "rash",
  "rashes",
  "infection",
  "infected",
  "fungal",
  "prescription",
  "prescribed",
  "antibiotic",
  "antibiotics",
  "accutane",
  "isotretinoin",
  "tretinoin",
  "tret",
  "steroid",
  "steroids",
  "eczema",
  "psoriasis",
  "rosacea",
  "dermatitis",
  "perioral",
  "hives",
  "cyst",
  "cysts",
  "cystic",
  "bleeding",
  "pain",
  "painful",
  "burning",
  "burns",
  "swollen",
  "swelling",
  "blister",
  "blisters",
  "allergic",
  "allergy",
  "melasma",
  "hair loss",
  "hair falling out",
  "bald",
  "balding",
  "alopecia",
  "doctor",
  "derm",
  "dermatologist",
];

/// A look for an occasion: makeup, ordered from the shelf, plus the
/// person's own saved looks as doors. The creative asks live here —
/// "make my going out look slay tonight".
export const LOOK_WORDS: readonly string[] = [
  "my look",
  "a look",
  "the look",
  "look for tonight",
  "going out look",
  "recreate",
  "recreate my",
  "slay",
  "slaying",
  "glam",
  "soft glam",
  "full glam",
  "full beat",
  "beat my face",
  "beat",
  "grwm",
  "get ready with me",
  "getting ready",
  "get ready",
  "makeup look",
  "no makeup makeup",
  "clean girl",
  "snatched",
  "glowy",
  "dewy look",
  "smokey eye",
  "smoky eye",
  "cut crease",
  "what should i wear",
  "what do i wear",
  "outfit",
];

/// Occasions read as "tonight, makeup" — a look, not a skincare routine.
export const OCCASION_WORDS: readonly string[] = [
  "tonight",
  "going out",
  "night out",
  "date night",
  "date",
  "party",
  "event",
  "wedding",
  "wedding guest",
  "club",
  "clubbing",
  "dinner",
  "brunch",
  "concert",
  "festival",
  "prom",
  "birthday",
  "girls night",
  "big night",
  "special occasion",
];

export const ROUTINE_WORDS: readonly string[] = [
  "routine",
  "routines",
  "regimen",
  "regime",
  "lineup",
  "line up",
  "line-up",
  "what order",
  "which order",
  "in what order",
  "order to use",
  "order to apply",
  "order should i",
  "what goes first",
  "what comes first",
  "what goes on first",
  "steps",
  "step by step",
  "skincare order",
  "layer my",
  "layering order",
  "put together",
  "set up my",
  "start my day",
  "before bed",
  "wind down",
  "skin cycling",
  "curly girl method",
  "cgm",
  "cg method",
  "refresh routine",
  "morning skincare",
  "night skincare",
  "am skincare",
  "pm skincare",
];

export const MISSING_WORDS: readonly string[] = [
  "missing",
  "gap",
  "gaps",
  "lacking",
  "what am i lacking",
  "what do i need",
  "what should i add",
  "what am i missing",
  "what's missing",
  "whats missing",
  "what is missing",
  "what's left",
  "what else do i need",
  "what else should i add",
  "do i need",
  "am i covered",
  "have everything",
  "complete my",
  "round out",
  "fill in",
  "what am i not using",
  "holes in my",
  "bare minimum",
  "basics",
  "the essentials",
  "starter kit",
  "beginner",
  "starting from scratch",
];

export const TRY_NEXT_WORDS: readonly string[] = [
  "try next",
  "should i try",
  "what to try",
  "worth trying",
  "recommend",
  "recommends",
  "recommendation",
  "recommendations",
  "recs",
  "rec",
  "suggest",
  "suggestion",
  "suggestions",
  "what's good",
  "whats good",
  "what is good",
  "what's best",
  "whats best",
  "the best",
  "what's worth",
  "worth it",
  "worth the hype",
  "worth the money",
  "hyped",
  "viral",
  "trending",
  "everyone's using",
  "everyone is using",
  "what should i get",
  "what should i buy",
  "what could i get",
  "what to buy",
  "what to get",
  "shopping list",
  "wishlist",
  "wish list",
  "haul",
  "next purchase",
  "add to cart",
  "looking for",
  "im looking for",
  "i'm looking for",
  "in the market for",
  "need a new",
  "want a new",
  "dupe",
  "dupes",
  "alternative to",
  "something like",
  "similar to",
  "cheaper version",
  "holy grail",
  "holy grails",
  "hg",
  "people like me use",
  "people like me",
  "what do people",
  "what are people",
  "top rated",
  "highest rated",
  "most popular",
  "new serum",
  "new cleanser",
  "new moisturizer",
  "new moisturiser",
  "new sunscreen",
  "new foundation",
  "new mascara",
  "new product",
  "new products",
];

export const COMPARE_WORDS: readonly string[] = [
  "compare",
  "comparison",
  "versus",
  "vs",
  "vs.",
  "which of my",
  "which one",
  "which is better",
  "which one's better",
  "which ones better",
  "better than",
  "best of my",
  "favorite",
  "favourite",
  "fave",
  "faves",
  "rank my",
  "my ranking",
  "winner",
  "which do i like",
  "which do i prefer",
  "top pick",
  "my top",
  "head to head",
  "face off",
  "face-off",
  "showdown",
];

export const CLASH_WORDS: readonly string[] = [
  "clash",
  "clashes",
  "conflict",
  "conflicts",
  "together",
  "at the same time",
  "same time",
  "mix",
  "mixing",
  "combine",
  "combining",
  "layer",
  "layering",
  "pair",
  "pairing",
  "pill",
  "pilling",
  "pills",
  "cancel out",
  "cancel each other",
  "too many actives",
  "safe to use with",
  "can i use with",
  "use both",
  "both of these",
  "stack",
  "stacking",
];

export const GREETING_WORDS: readonly string[] = [
  "hi",
  "hey",
  "hello",
  "yo",
  "hiya",
  "hola",
  "sup",
  "good morning",
  "good evening",
  "good night",
  "thanks",
  "thank you",
  "ty",
  "thx",
  "ok",
  "okay",
  "cool",
  "nice",
];

/// The words that decide a routine's slot. "tonight" leans pm here too,
/// but only after LOOK has had its chance.
export const SLOT_WORDS: Record<"am" | "pm" | "weekly" | "wash_day", readonly string[]> = {
  am: [
    "morning",
    "mornings",
    "am",
    "a.m.",
    "daytime",
    "day time",
    "before work",
    "wake up",
    "start my day",
    "in the morning",
  ],
  pm: [
    "night",
    "nights",
    "evening",
    "evenings",
    "pm",
    "p.m.",
    "bed",
    "bedtime",
    "before bed",
    "tonight",
    "nighttime",
    "night time",
    "wind down",
    "after work",
    "sleep",
  ],
  weekly: [
    "weekly",
    "once a week",
    "sunday",
    "sundays",
    "self care day",
    "self-care day",
    "reset",
    "deep clean",
    "mask day",
  ],
  wash_day: [
    "wash day",
    "washday",
    "curly girl method",
    "cgm",
    "cg method",
    "wash-day",
    "wash days",
    "hair wash",
    "washing my hair",
    "shower day",
    "cowash",
    "co-wash",
    "co wash",
    "plopping",
    "diffusing",
  ],
};

export const DOMAIN_WORDS: Record<
  "haircare" | "makeup" | "skincare" | "fragrance",
  readonly string[]
> = {
  haircare: [
    "hair",
    "curl",
    "curls",
    "curly",
    "coils",
    "coily",
    "wavy",
    "waves",
    "scalp",
    "frizz",
    "frizzy",
    "shampoo",
    "conditioner",
    "leave in",
    "leave-in",
    "gel cast",
    "cast",
    "diffuse",
    "refresh day",
    "wash day",
    "3a",
    "3b",
    "3c",
    "4a",
    "4b",
    "4c",
    "2a",
    "2b",
    "2c",
  ],
  makeup: [
    "makeup",
    "make-up",
    "make up",
    "glam",
    "beat",
    "face beat",
    "foundation",
    "concealer",
    "blush",
    "bronzer",
    "contour",
    "highlighter",
    "mascara",
    "eyeliner",
    "eyeshadow",
    "brows",
    "lipstick",
    "lip gloss",
    "setting spray",
    "primer",
    "base",
    "full face",
    "everyday face",
  ],
  skincare: [
    "skin",
    "skincare",
    "skin care",
    "face",
    "cleanser",
    "serum",
    "moisturizer",
    "moisturiser",
    "sunscreen",
    "spf",
    "toner",
    "actives",
    "retinol",
    "exfoliate",
    "exfoliant",
    "glass skin",
    "barrier",
    "slugging",
    "double cleanse",
  ],
  fragrance: [
    "fragrance",
    "perfume",
    "scent",
    "cologne",
    "signature scent",
    "smell",
  ],
};

/// Words a person uses for a category, beyond its slug and label. Keys are
/// the top-level `categories.slug`s.
export const CATEGORY_WORDS: Record<string, readonly string[]> = {
  serum: [
    "serum",
    "serums",
    "active",
    "actives",
    "treatment serum",
    "vitamin c",
    "niacinamide",
    "hyaluronic",
    "retinol",
    "retinal",
    "peptide",
    "peptides",
  ],
  foundation: [
    "foundation",
    "foundations",
    "base",
    "skin tint",
    "tinted moisturizer",
    "bb cream",
    "cc cream",
    "complexion",
  ],
  cleanser: [
    "cleanser",
    "cleansers",
    "face wash",
    "facewash",
    "wash",
    "cleansing balm",
    "oil cleanser",
    "micellar",
    "double cleanse",
  ],
  moisturizer: [
    "moisturizer",
    "moisturiser",
    "moisturizers",
    "moisturisers",
    "cream",
    "face cream",
    "night cream",
    "gel cream",
    "lotion",
    "hydrator",
    "occlusive",
    "slugging",
  ],
  sunscreen: [
    "sunscreen",
    "sunscreens",
    "spf",
    "sun",
    "sunblock",
    "sun cream",
    "sun protection",
    "uv",
  ],
  toner: ["toner", "toners", "essence", "essences", "mist", "face mist", "hydrating toner"],
  exfoliant: [
    "exfoliant",
    "exfoliants",
    "exfoliator",
    "exfoliate",
    "acid",
    "acids",
    "aha",
    "bha",
    "pha",
    "glycolic",
    "lactic",
    "salicylic",
    "peel",
    "peeling",
    "scrub",
  ],
  styler: [
    "styler",
    "stylers",
    "curl cream",
    "gel",
    "mousse",
    "leave in",
    "leave-in",
    "leave-in conditioner",
    "custard",
    "foam",
    "hair oil",
    "hair gel",
    "cream gel",
    "definer",
    "hold",
  ],
  shampoo: ["shampoo", "shampoos", "clarifying", "low poo", "lo-poo", "cowash", "co-wash"],
  conditioner: [
    "conditioner",
    "conditioners",
    "deep conditioner",
    "hair mask",
    "rinse out",
    "rinse-out",
  ],
  fragrance: [
    "fragrance",
    "fragrances",
    "perfume",
    "perfumes",
    "scent",
    "scents",
    "cologne",
    "edp",
    "edt",
    "body mist",
  ],
  lip: [
    "lip",
    "lips",
    "lipstick",
    "lipsticks",
    "gloss",
    "lip gloss",
    "lip oil",
    "lip liner",
    "lip tint",
    "lippie",
  ],
  mascara: ["mascara", "mascaras", "lashes"],
  blush: ["blush", "blushes", "blusher", "cream blush", "liquid blush"],
  concealer: ["concealer", "concealers", "under eye", "undereye", "dark circles"],
  bronzer: ["bronzer", "bronzers", "contour", "contouring"],
  highlighter: ["highlighter", "highlighters", "highlight", "glow", "glowy"],
  eyeshadow: [
    "eyeshadow",
    "eyeshadows",
    "shadow",
    "palette",
    "palettes",
    "eye look",
    "smokey eye",
    "smoky eye",
  ],
  eyeliner: ["eyeliner", "eyeliners", "liner", "wing", "winged liner", "kohl"],
  brow: ["brow", "brows", "eyebrow", "eyebrows", "brow gel", "brow pencil"],
  primer: ["primer", "primers", "gripping primer", "pore filler"],
  setting: [
    "setting spray",
    "setting powder",
    "powder",
    "finishing powder",
    "translucent powder",
    "bake",
    "baking",
  ],
  mask: ["mask", "masks", "sheet mask", "clay mask", "face mask"],
  eye: ["eye cream", "eye creams", "eye serum", "eye gel"],
  treatment: [
    "treatment",
    "treatments",
    "spot",
    "spot treatment",
    "pimple patch",
    "patches",
    "targeted",
  ],
  scalp: ["scalp", "scalp serum", "scalp scrub", "scalp oil"],
  lipcare: ["lip balm", "lip mask", "lip scrub", "chapstick"],
  body: ["body lotion", "body wash", "body cream", "body oil", "body care"],
  device: ["gua sha", "jade roller", "led mask", "device", "tool"],
  haircolor: ["hair dye", "dye", "bleach", "toner for hair", "color", "colour"],
  tools: ["brush", "brushes", "sponge", "beauty blender", "beautyblender"],
  lashes: ["false lashes", "falsies", "lash extensions", "lash lift"],
};

function escape(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

const cache = new Map<string, RegExp>();

/// Whole-word match for a phrase: "spf" in "spf?" yes, "am" in "cream" no.
/// Hyphens and spaces in the phrase match either in the text.
export function hasWord(text: string, phrase: string): boolean {
  let re = cache.get(phrase);
  if (!re) {
    const body = phrase.split(/[\s-]+/).map(escape).join("[\\s-]+");
    re = new RegExp(`(?:^|[^a-z0-9])${body}(?=$|[^a-z0-9])`);
    cache.set(phrase, re);
  }
  return re.test(text);
}

/// The longest phrase from the list found in the text, or null.
export function longestMatch(text: string, phrases: readonly string[]): string | null {
  let best: string | null = null;
  for (const p of phrases) {
    if ((best === null || p.length > best.length) && hasWord(text, p)) best = p;
  }
  return best;
}

export function hasAny(text: string, phrases: readonly string[]): boolean {
  return longestMatch(text, phrases) !== null;
}
